version: '2'
services:
    web:
      build: ./web/
      expose:
        - "5000"
      volumes:
        - /app/static
      env_file:
        - ./web/.env
        - ./web/common.env
      command: python /app/reverse_twitter/app.py --config=/app/reverse_twitter/etc/config 
      links:
        - db

    nginx:
      build: ./nginx/
      ports:
        - "80:80"
      volumes_from:
        - web
      links:
        - web:web

    db:
      build: ./rethinkdb/
