web:
  restart: always
  build: ./web/
  expose:
    - "5000"
  volumes:
    - /app/static
  environment:
    - SECRET_KEY=foobar 
    - CONSUMER_KEY=8nnQiHg720tPYZBjPY8R7w 
    - CONSUMER_SECRET=PiuOvQUanC5LfRESG7C2aTjqWPcAT53uHurRY8Sj94 
    - PYTHONPATH=$PYTHONPATH:/app/
  command: python /app/reverse_twitter/app.py --config=/app/reverse_twitter/etc/config 

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web
