web:
  restart: always
  build: ./web/
  expose:
    - "5000"
  volumes:
    - /app/static
  env_file:
    - ./web/.env
    - ./web/common.env
  command: python /app/reverse_twitter/app.py --config=/app/reverse_twitter/etc/config 

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:web
